export default {
  pages: [
    'pages/home/index',
    'pages/doll-list/index',
    'pages/doll-detail/index',
    'pages/accessory-list/index',
    'pages/accessory-detail/index',
    'pages/outfit-list/index',
    'pages/outfit-detail/index',
    'pages/outfit-create/index',
    'pages/cart/index',
    'pages/profile/index',
    'pages/login/index',
    'pages/profile/profile/index',
    'pages/profile/favorites/index',
    'pages/profile/history/index',
    'pages/profile/inquiries/index',
    'pages/address/index',
    'pages/address/edit',
    'pages/company/index',
    'pages/order-confirm/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#ffffff',
    navigationBarTitleText: '娃娃',
    navigationBarTextStyle: 'black',
  },
  tabBar: {
    color: '#999999',
    selectedColor: '#f43f5e',
    backgroundColor: '#ffffff',
    borderStyle: 'black',
    list: [
      { pagePath: 'pages/home/index', text: '首页' },
      { pagePath: 'pages/doll-list/index', text: '娃娃' },
      { pagePath: 'pages/company/index', text: '企业' },
      { pagePath: 'pages/cart/index', text: '购物车' },
      { pagePath: 'pages/profile/index', text: '我的' },
    ],
  },
}
